# Generated by Django 6.0.4 on 2026-05-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('variety', models.CharField(choices=[('Koroneiki', 'Koroneiki'), ('Arbequina', 'Arbequina'), ('Picual', 'Picual'), ('Frantoio', 'Frantoio')], max_length=50)),
                ('tree_count', models.IntegerField()),
                ('area_hectares', models.FloatField()),
                ('planting_year', models.IntegerField()),
                ('irrigation_type', models.CharField(default='Drip', max_length=50)),
                ('soil_type', models.CharField(default='Loam', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Dormant', 'Dormant'), ('New', 'New Planting')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
